server:
  port: 8081

spring:
  application:
    name: zijin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_school?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT
    username: root
    password: root
    hikari:
      # 最小连接数
      minimum-idle: 1
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 10000
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 连接测试查询语句
      connection-test-query: SELECT 1
  #redis配置数据
  redis:
    database: 3
    password:
    port: 6379
    host: localhost
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
  #Mybatis-Plus配置
  mybatis-plus:
    # mapper映射文件路径
    mapper-locations: classpath:mapper/*.xml
    # pojo类所在包路径
    type-aliases-package: com.example.zijin.entity
    global-config:
      db-config:
      #主键类型：auto主键自增，input用户输入id，id_worker全局唯一的数字id，UUID全局唯一的UUID
      id-type: auto
      #开启驼峰式转换
      table-underline: true

#阿里云短信服务
  sms:
    ali:
      product: Dysmsapi
      domain: dysmsapi.aliyuncs.com
      signName: 金色传说                #你设置的签名名称
      accessKeyId: LTAI4FuNH3cQirWwhynvdCxv            #阿里云给你的key
      accessKeySecret: TmUIP6EkFBi5c9Mrq5kysWMRsNe7x6     #阿里云给你的密钥